### ISSUE TITLE
Request / Load webfonts from global CDN 

### ISSUE THREAD

**Issue by o-hook** [porscheui/porsche-ui-contribution#20]
**Scope**  
Webfonts are hosted on Porsche UI CDN. Update relative SCSS webfont paths to global CDN path: https://cdn.ui.porsche.com/porsche-ui-kit/font/v1

**Tasks**
- [x] Update paths in UI Kit Core
- [x] Update UI Kit Core dependenciy in UI Kit React after publishing Core
- [x] Test loading in Core and React
