### ISSUE TITLE
Contribution / external vs. internal links

### ISSUE THREAD

**Issue by oliviapala** [porscheui/porsche-ui-contribution#27]
**Scope**  
**Question from the Uiux-Guild:**
Hi guild, do we have a common approach to mark links that open new tabs(external pages) e.g. with an icon? If we mark links that open external pages e.g. google maps.
I meant for usability purpose, because we had some findings that people are confused or didn’t notice that they are now on a new page. They tried to use the browser back button. We try to make it more obvious

**Notes**  
https://ux.stackexchange.com/questions/4636/external-links-whether-how-to-distinguishing-them-from-internal-links-and-to

**Props** (if relevant)  
- Name: Text link / linked text

**Subtasks**  
- [ ] Create UI decision proposal based on research and testing
- [ ] Definition of hierarchy structure and naming of all related states and variants in design and code
- [ ] Approve UI definition
- [ ] Create/update Sketch library symbol in Abstract and share collection link
- [ ] Create UI/UX guidelines as .mdx
- [ ] Create/update related code CSS / JS
- [ ] Create samples of all possible states and variants
- [ ] Create Code/Implementation guidelines as .mdx for corresponding component code
- [ ] Create VRT and Unit test
- [ ] Test code visual and functional for optimized viewports (only one browser): 320px, 375px, 480px, 768px, 1024px, 1366px, 1920px
- [ ] Test code visual and functional for all supported browsers in viewports: 320px, 480px, 760px, 1000px, 1300px, 1760px, 1920px
